[versions."1.2.0"]
git = "https://github.com/webmproject/libwebp"
commit = "fedac6cc69cda3e9e04b780d324cf03921fb3ff4"

[versions."1.3.0-rc1"]
git = "https://github.com/webmproject/libwebp"
commit = "b557776962a3dcc985d83bd4ed94e1e2e50d0fa2"

[versions."1.3.1-rc1"]
git = "https://github.com/webmproject/libwebp"
commit = "7f0a341943c4af7d153959c8d365e0ed4d73f609"

[versions."1.3.1-rc2"]
git = "https://github.com/webmproject/libwebp"
commit = "fd7bb21c0cb56e8a82e9bfa376164b842f433f3b"

[versions."1.5.0-rc1"]
git = "https://github.com/webmproject/libwebp"
commit = "25e17c686f58e7061e300f4c649025f8ca7d1f34"

[versions."1.3.2"]
git = "https://github.com/webmproject/libwebp"
commit = "ca332209cb5567c9b249c86788cb2dbf8847e760"

[versions."1.2.3"]
git = "https://github.com/webmproject/libwebp"
commit = "62b45bddcd462b7749348be671fb20e75489be11"

[versions."1.0.2"]
git = "https://github.com/webmproject/libwebp"
commit = "2b98df90cb75cfc1cf4505a59a7b25499fa10887"

[versions."1.2.2"]
git = "https://github.com/webmproject/libwebp"
commit = "f035d2e40d4c314f8c70b868c21bd9d4f8466bb4"

[versions."1.2.2-rc2"]
git = "https://github.com/webmproject/libwebp"
commit = "9195ea0538bac4ac35966efc9451fefc4591998e"

[versions."1.0.3"]
git = "https://github.com/webmproject/libwebp"
commit = "0fe1a89dbf1930fc2554dbe76adad5d962054ead"

[versions."1.4.0"]
git = "https://github.com/webmproject/libwebp"
commit = "cc34288aa39a24a8a552126ad747121275f19b48"

[versions."1.4.0-rc1"]
git = "https://github.com/webmproject/libwebp"
commit = "cc34288aa39a24a8a552126ad747121275f19b48"

[versions."1.6.0-rc1"]
git = "https://github.com/webmproject/libwebp"
commit = "6a3e656b6d2c4380bd259b753adcfb86ba6ad8b9"

[versions."1.2.2-rc1"]
git = "https://github.com/webmproject/libwebp"
commit = "f035d2e40d4c314f8c70b868c21bd9d4f8466bb4"

[versions."1.2.1"]
git = "https://github.com/webmproject/libwebp"
commit = "731246ba3bcb755de86dcd85c6bd8381b7012863"

[versions."1.3.0"]
git = "https://github.com/webmproject/libwebp"
commit = "b557776962a3dcc985d83bd4ed94e1e2e50d0fa2"

[versions."1.2.4"]
git = "https://github.com/webmproject/libwebp"
commit = "0d1f12546bd803099a60c070517a552483f3790e"

[versions."1.0.1"]
git = "https://github.com/webmproject/libwebp"
commit = "e85d3313d6d52b1e9c6c181b488fc0831a747de8"

[versions."1.1.0"]
git = "https://github.com/webmproject/libwebp"
commit = "d7844e9762b61c9638c263657bd49e1690184832"

[versions."1.2.3-rc1"]
git = "https://github.com/webmproject/libwebp"
commit = "62b45bddcd462b7749348be671fb20e75489be11"

[versions."1.6.0"]
git = "https://github.com/webmproject/libwebp"
commit = "6a3e656b6d2c4380bd259b753adcfb86ba6ad8b9"

[versions."1.5.0"]
git = "https://github.com/webmproject/libwebp"
commit = "25e17c686f58e7061e300f4c649025f8ca7d1f34"

[versions."1.3.1"]
git = "https://github.com/webmproject/libwebp"
commit = "7f0a341943c4af7d153959c8d365e0ed4d73f609"
