[versions."1.91.6"]
git = "https://github.com/ocornut/imgui"
commit = "947aa9c9722bd6ff740dd757da609ff41f4d3ba3"

[versions."1.92.1"]
git = "https://github.com/ocornut/imgui"
commit = "44aa9a4b3a6f27d09a4eb5770d095cbd376dfc4b"

[versions."1.92.1-docking"]
git = "https://github.com/ocornut/imgui"
commit = "44aa9a4b3a6f27d09a4eb5770d095cbd376dfc4b"

[versions."1.92.5"]
git = "https://github.com/ocornut/imgui"
commit = "3912b3d9a9c1b3f17431aebafd86d2f40ee6e59c"

[versions."1.91.9"]
git = "https://github.com/ocornut/imgui"
commit = "126d004f9e1eef062bf4b044b3b2faaf58d48c51"

[versions."1.92.0-docking"]
git = "https://github.com/ocornut/imgui"
commit = "adfa5364cd84db127f8f5d093be90c2e3608be0f"

[versions."1.92.2b"]
git = "https://github.com/ocornut/imgui"
commit = "45acd5e0e82f4c954432533ae9985ff0e1aad6d5"

[versions."1.92.5-docking"]
git = "https://github.com/ocornut/imgui"
commit = "3912b3d9a9c1b3f17431aebafd86d2f40ee6e59c"

[versions."1.91.7"]
git = "https://github.com/ocornut/imgui"
commit = "c0ae3258f9da5b959b214213ffe37ab36ea7f76f"

[versions."1.92.6"]
git = "https://github.com/ocornut/imgui"
commit = "2a1b69f05748ad909f03acf4533447cac1331611"

[versions."1.92.4-docking"]
git = "https://github.com/ocornut/imgui"
commit = "e7d2d636affeeac1fc7175fb13472ca02d1bc0d1"

[versions."1.91.5"]
git = "https://github.com/ocornut/imgui"
commit = "368123ab06b2b573d585e52f84cd782c5c006697"

[versions."1.92.2-docking"]
git = "https://github.com/ocornut/imgui"
commit = "031a18c417158427217bc5890e0ec0cb7e7b4b63"

[versions."1.92.3-docking"]
git = "https://github.com/ocornut/imgui"
commit = "62275e877a691bd2e51d1ca86bdfed49fa5cb297"

[versions."1.91.9b-docking"]
git = "https://github.com/ocornut/imgui"
commit = "4806a1924ff6181180bf5e4b8b79ab4394118875"

[versions."1.92.2"]
git = "https://github.com/ocornut/imgui"
commit = "031a18c417158427217bc5890e0ec0cb7e7b4b63"

[versions."1.92.4"]
git = "https://github.com/ocornut/imgui"
commit = "e7d2d636affeeac1fc7175fb13472ca02d1bc0d1"

[versions."1.91.8"]
git = "https://github.com/ocornut/imgui"
commit = "11b3a7c8ca23201294464c7f368614a9106af2a1"

[versions."1.92.2b-docking"]
git = "https://github.com/ocornut/imgui"
commit = "1f7f1f54af38b0350d8c0008b096a9af6de299c7"

[versions."1.92.0"]
git = "https://github.com/ocornut/imgui"
commit = "adfa5364cd84db127f8f5d093be90c2e3608be0f"

[versions."1.92.3"]
git = "https://github.com/ocornut/imgui"
commit = "62275e877a691bd2e51d1ca86bdfed49fa5cb297"

[versions."1.92.6-docking"]
git = "https://github.com/ocornut/imgui"
commit = "2a1b69f05748ad909f03acf4533447cac1331611"

[versions."1.92.7-docking"]
git = "https://github.com/ocornut/imgui"
commit = "b1bcb12a624af7509894c8e77dd47416997777fa"

[versions."1.92.7"]
git = "https://github.com/ocornut/imgui"
commit = "b1bcb12a624af7509894c8e77dd47416997777fa"
