[versions."10.0.0"]
git = "https://github.com/leethomason/tinyxml2"
commit = "321ea883b7190d4e85cae5512a12e5eaa8f8731f"

[versions."5.0.0"]
git = "https://github.com/leethomason/tinyxml2"
commit = "81b219446220f5475ff4b5eaf9b21d99b8c4ed6b"

[versions."7.0.0"]
git = "https://github.com/leethomason/tinyxml2"
commit = "397f22581b6f3969208f2cc41f36d4b39c39ad39"

[versions."6.0.0"]
git = "https://github.com/leethomason/tinyxml2"
commit = "8c8293ba8969a46947606a93ff0cb5a083aab47a"

[versions."6.2.0"]
git = "https://github.com/leethomason/tinyxml2"
commit = "c1424ee4e1c1ed8129d9147ccc920ab92dd9ef86"

[versions."2.0.1"]
git = "https://github.com/leethomason/tinyxml2"
commit = "686ef404b8718ab4fa40c2f10633a1f69375c20d"

[versions."5.0.1"]
git = "https://github.com/leethomason/tinyxml2"
commit = "37bc3aca429f0164adf68c23444540b4a24b5778"

[versions."7.0.1"]
git = "https://github.com/leethomason/tinyxml2"
commit = "de6d164822076f9b1e26a7222808a25ac03867d8"

[versions."4.0.1"]
git = "https://github.com/leethomason/tinyxml2"
commit = "74d44acb176f8510abf28ee0a70961eb26631988"

[versions."7.1.0"]
git = "https://github.com/leethomason/tinyxml2"
commit = "9c740e8d2341bd46dbe8e87053cdb4d931971967"

[versions."8.1.0"]
git = "https://github.com/leethomason/tinyxml2"
commit = "3291390336141573e51dfa991b4179c8bcd8f306"

[versions."2.1.0"]
git = "https://github.com/leethomason/tinyxml2"
commit = "6ee53e7d49a4dbfd5c1d7e67fb0228703bbe7309"

[versions."4.0.0"]
git = "https://github.com/leethomason/tinyxml2"
commit = "6ba2a077ed575f05c0fa147bc56f4aa41f908b80"

[versions."8.0.0"]
git = "https://github.com/leethomason/tinyxml2"
commit = "bf15233ad88390461f6ab0dbcf046cce643c5fcb"

[versions."9.0.0"]
git = "https://github.com/leethomason/tinyxml2"
commit = "1dee28e51f9175a31955b9791c74c430fe13dc82"

[versions."10.1.0"]
git = "https://github.com/leethomason/tinyxml2"
commit = "57eea48c5bfc354ac45d53b2eb499e66c80d63e0"

[versions."11.0.0"]
git = "https://github.com/leethomason/tinyxml2"
commit = "9148bdf719e997d1f474be6bcc7943881046dba1"

[versions."2.2.0"]
git = "https://github.com/leethomason/tinyxml2"
commit = "5321a0e21f111536e17fbff81b51e30acdcd8738"

[versions."2.0.2"]
git = "https://github.com/leethomason/tinyxml2"
commit = "b59ac45131eab3ad1f53b0d3ec60a98e8a96230a"

[versions."3.0.0"]
git = "https://github.com/leethomason/tinyxml2"
commit = "1977a7258cc66fd4da7f1e9da05a4933646a7803"
