[versions."1.2.0"]
git = "https://github.com/libsndfile/libsndfile"
commit = "2ed38b57c5838ba6b7c8e726a62855845bd42ec5"

[versions."1.2.2"]
git = "https://github.com/libsndfile/libsndfile"
commit = "72f6af15e8f85157bd622ed45b979025828b7001"

[versions."1.1.0"]
git = "https://github.com/libsndfile/libsndfile"
commit = "dfdad63ff2c792299d3553f04153afe7f695033a"

[versions."1.0.28"]
git = "https://github.com/libsndfile/libsndfile"
commit = "1d928bffdb65e827c3e7d17ece0e123b4a70ec6c"

[versions."1.0.31"]
git = "https://github.com/libsndfile/libsndfile"
commit = "d60deb5d8691997b6bb28d88e3b43f322073d146"

[versions."1.0.25"]
git = "https://github.com/libsndfile/libsndfile"
commit = "2c4d2bdce6271fb1dc7df67363cf33cc04c67917"

[versions."1.0.26"]
git = "https://github.com/libsndfile/libsndfile"
commit = "f67f0992eae3d19ca3a3804c8ea6b081b2131e5f"

[versions."1.0.27"]
git = "https://github.com/libsndfile/libsndfile"
commit = "d3d545abf9ed5542b69ded164b36a28338340a6b"

[versions."1.0.29"]
git = "https://github.com/libsndfile/libsndfile"
commit = "ccb75f48293644085741dcbb54e6501b46717a0e"

[versions."1.0.30"]
git = "https://github.com/libsndfile/libsndfile"
commit = "68958f9c9199dad97dcd10700df3746b2cd9b8a3"

[versions."1.1.0beta2"]
git = "https://github.com/libsndfile/libsndfile"
commit = "f1495b4bcc4f7f0fedb10119e6b5b5b2f1946d4b"

[versions."1.0.28pre1"]
git = "https://github.com/libsndfile/libsndfile"
commit = "500b503cb3a1ca4149b02b399931d83d2838c5f3"

[versions."1.1.0beta1"]
git = "https://github.com/libsndfile/libsndfile"
commit = "dfdad63ff2c792299d3553f04153afe7f695033a"

[versions."1.2.1"]
git = "https://github.com/libsndfile/libsndfile"
commit = "34998eaf15c10c37800f116c4833b944b5063ada"
