[versions."1.2.0rc2"]
git = "https://github.com/google/brotli"
commit = "8ca2312c61f1f5853be0708f9b1d6a6ad002d2a4"

[versions."1.0.7"]
git = "https://github.com/google/brotli"
commit = "d6d98957ca8ccb1ef45922e978bb10efca0ea541"

[versions."0.6.0"]
git = "https://github.com/google/brotli"
commit = "46c1a881b41bb638c76247558aa04b1591af3aa7"

[versions."1.0.2"]
git = "https://github.com/google/brotli"
commit = "0ad94eed00420bf1154cb16a289aa27efbb30c01"

[versions."1.0.9"]
git = "https://github.com/google/brotli"
commit = "e61745a6b7add50d380cfd7d3883dd6c62fc2c71"

[versions."1.2.0"]
git = "https://github.com/google/brotli"
commit = "34e43eb020babe4a6eb2ef9b5edfdac8cade4b18"

[versions."1.1.0rc"]
git = "https://github.com/google/brotli"
commit = "2a5a088b03ba5fd3aab4f34338c84e2c61d82c49"

[versions."0.2.0"]
git = "https://github.com/google/brotli"
commit = "7f7a2fb48cec63c0459ec6b6e7260810bfb01819"

[versions."0.3.0"]
git = "https://github.com/google/brotli"
commit = "98ed7a23a83d64133b0a36a884e489bffb0eb864"

[versions."1.1.1"]
git = "https://github.com/google/brotli"
commit = "4cb7828376e1e5ec333aae9f851b7b35e6f15040"

[versions."1.0.0"]
git = "https://github.com/google/brotli"
commit = "c60563591a9a86196f19987c81dde4384a088861"

[versions."1.2.0rc1"]
git = "https://github.com/google/brotli"
commit = "34e43eb020babe4a6eb2ef9b5edfdac8cade4b18"

[versions."0.4.0"]
git = "https://github.com/google/brotli"
commit = "29d31d5921b0a2b323ac24e7f7d0cdc9a3c0dd08"

[versions."0.5.2"]
git = "https://github.com/google/brotli"
commit = "66c14517cf8afcc1a1649a7833ac789366eb0b51"

[versions."1.0.5"]
git = "https://github.com/google/brotli"
commit = "b601fe817bd3217cb144bbb380a43cae8e847388"

[versions."0.1.0"]
git = "https://github.com/google/brotli"
commit = "d811b186c5037b434d56ddb831ceccdf5a954687"

[versions."1.0.3"]
git = "https://github.com/google/brotli"
commit = "533843e3546cd24c8344eaa899c6b0b681c8d222"

[versions."1.0.6"]
git = "https://github.com/google/brotli"
commit = "6eba239a5bb553fd557b7d78f7da8f0059618b9e"

[versions."1.1.0"]
git = "https://github.com/google/brotli"
commit = "9c91b6a295b9074a1ad78956c72c23b897cd0080"

[versions."1.0.4"]
git = "https://github.com/google/brotli"
commit = "c6333e1e79fb62ea088443f192293f964409b04e"

[versions."1.0.8"]
git = "https://github.com/google/brotli"
commit = "db361a0bb901d6a71c7cbf1370d97b3703482e3b"

[versions."1.0.1"]
git = "https://github.com/google/brotli"
commit = "5b4769990dc14a2bd466d2599c946c5652cba4b2"
