[versions."1.3.0"]
git = "https://github.com/USCiLab/cereal"
commit = "02eace19a99ce3cd564ca4e379753d69af08c2c8"

[versions."1.2.2"]
git = "https://github.com/USCiLab/cereal"
commit = "51cbda5f30e56c801c07fe3d3aba5d7fb9e6cca4"

[versions."1.1.1"]
git = "https://github.com/USCiLab/cereal"
commit = "94d49c42acfb3dfac495f9610008140d78aecec7"

[versions."1.1.2"]
git = "https://github.com/USCiLab/cereal"
commit = "2f9471bc401590cf58b38bbbc33d412dade6d589"

[versions."0.9.0"]
git = "https://github.com/USCiLab/cereal"
commit = "8375dbca75a84f2a67682a0fc3ee4bb4c3eef133"

[versions."1.1.0"]
git = "https://github.com/USCiLab/cereal"
commit = "81ec2714ea969bbf01330bf84917022473cff032"

[versions."0.9.1"]
git = "https://github.com/USCiLab/cereal"
commit = "8af446865231b6cf16c4f7cae4de162eb0f9a55c"

[versions."1.0.0"]
git = "https://github.com/USCiLab/cereal"
commit = "3bbe6bde37431c842acd905f55ef5aa2a45f3e8f"

[versions."1.2.1"]
git = "https://github.com/USCiLab/cereal"
commit = "bd839ccb47dfb5462331fede7c5f013ca8dc60cb"

[versions."1.3.1"]
git = "https://github.com/USCiLab/cereal"
commit = "1de8fe89471d69ea392ea260ce74e079d5f4b415"

[versions."1.3.2"]
git = "https://github.com/USCiLab/cereal"
commit = "ebef1e929807629befafbb2918ea1a08c7194554"

[versions."1.2.0"]
git = "https://github.com/USCiLab/cereal"
commit = "42a45b6e15fcbd1a3d65b033f5d4d0b2ef6c023d"
