[versions."2.10.19"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "411a109150b270f23c8c97fa4ec9a0a4a98cdecf"

[versions."2.10.4"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "29e23c253b63bd753923c3822fc9051a67399fc3"

[versions."2.10.10"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "91f66c625b6361d2edabf76eae30887b326b2447"

[versions."2.10.14"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "6f602bee67b088a299d7901534af3bce6334ab38"

[versions."2.10.15"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "b94bc32ff84e815ba44c567f6fe4af5f5f6b3048"

[versions."2.10.12"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "d4fb1cf7f7d22c12e2e442ba5a5e98d09b0a28ab"

[versions."2.10.9"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "8f0393dd7be08f2d9b44cc09b8b97f9bafb109a5"

[versions."2.10.5"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "25d6b26f7038eeec3b51e2e0a70960a8e34fcd68"

[versions."2.10.7"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "c4cef129e880a3f9c23a480e8c983793963173bb"

[versions."2.10.6"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "66e50f02dde92f802bbd3a8d79c6352954665b9b"

[versions."2.10.1"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "e8dda215426172cd348e4d6d455141f40768bf47"

[versions."2.10.13"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "9d8f544001cb74544de6dc8c565592f7e2626d6e"

[versions."2.10.2"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "fea848e2a77563cf2a6f28f8eab396fd6e787fbf"

[versions."2.10.0"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "28919d0e127fc8d5cf57fae2db5d1b92b4eab381"

[versions."2.10.18"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "122d09549201da5383321d870bed45ecb9e168c5"

[versions."2.10.11"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "a325079f7e1976e0485a212d8921ce9b837c1f2f"

[versions."2.10.17"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "41e7d0074b6cb5b22c89f835b4531d848ab66987"

[versions."2.10.3"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "e388a2e523f4d0b6aee2bb923637d82d8b969556"

[versions."2.10.16"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "18212a2a7967e12d740bfb957e500892b3463c88"

[versions."2.10.8"]
git = "https://github.com/microsoft/cpprestsdk"
commit = "204a52610234ac5180e80a6883b62c0ad085f51e"
