[versions."1.0.49"]
git = "https://github.com/user-with-username/example_lib.git"
commit = "c209bf1df6600ebf380d475145559fe03176ff3e"

[versions."1.0.411"]
git = "https://github.com/user-with-username/example_lib.git"
commit = "c209bf1df6600ebf380d475145559fe03176ff3e"

[versions."1.0.4"]
git = "https://github.com/user-with-username/example_lib.git"
commit = "c209bf1df6600ebf380d475145559fe03176ff3e"
